Use redux in components bookStore-CMS project
juaryimami/book-store-react pull request #4
Opened 2022-11-08 13:27 UTC by juaryimami

### In this stage
---
-  I use `Redux` store to display books.
- I also add some `UI` elements to my components and make them dispatch actions
---
#### Thank you for reviewing my project!!!!.

2022-11-08 13:50 UTC, addod19 requested changes
### Hi @juaryimami, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Adding and removing book is successful :100: 
- [ ] Redux set up properly :1st_place_medal: 
- [ ] Component for adding book present :rocket: 
- [ ] Git-flow followed :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-08 13:50 UTC, addod19 commented on src/redux/store.js
>  import { configureStore } from '@reduxjs/toolkit';
- [ ] It would be better if our inputs(title, author) updates the local state every time they update. We can achieve this by adding the (onChange) attributes

2022-11-08 13:50 UTC, addod19 commented on src/redux/store.js
- [ ] It would be better if we implement this functionality 
```
**submitBookToStore** takes the inputs from the state and generate a unique `id` and add them to an object, then dispatches the `addBook` action creator with the object as its argument
```

2022-11-08 13:50 UTC, addod19 commented on src/redux/store.js
>  export default configureStore({
- [ ] It would be better if our button would use a function `checkCategoriesStatus`. This function is responsible for dispatching the `underConstruction` action creator

2022-11-08 14:37 UTC, juaryimami commented on src/redux/store.js
am not understanding

2022-11-08 14:54 UTC, juaryimami commented on src/redux/store.js
>  import { configureStore } from '@reduxjs/toolkit';
I did not completely agree with this idea its is a form and it needs to be submitted. so  onSubmit is preferable

2022-11-08 14:59 UTC, juaryimami commented on src/redux/store.js
>  export default configureStore({
ok I will update it soon

2022-11-08 17:28 UTC, alexander16108 approved these changes
Hi @juaryimami , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/oCmX7HGo1qnzhEBiRF/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-09 12:51 UTC, merged

2022-12-12 13:13 UTC, ichala reviewed
Hi @juaryimami   ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Project Already Approved ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._