Style added book-store-CMS react project
juaryimami/book-store-react pull request #6
Opened 2022-11-10 14:42 UTC by juaryimami

### This is the last project of the Bookstore website:-
---
 - The functionality is done. 
 - I have to added styling. 
 - I use `Zeplin` as a collaboration tool.
 ---
#### Thank your for reviewing my project!!!!.

2022-11-10 17:34 UTC, DammyShittu requested changes
Hi @juaryimami,

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-10 17:34 UTC, DammyShittu commented on package.json
> +    "test": "craco test",
- [ ] I was unable to start up your project. See the error I get. Kindly fix that. I would recommend you stick to the CRA `react-scripts` commands.

  ![tyu](https://user-images.githubusercontent.com/54848363/201165309-b9882e45-6a25-407a-be38-6cee0d955bc8.jpg)

- [ ] This is what your app looks like after I change the commands to `react-scripts`. Kindly ensure your styling matches the design exactly after fixing the issues above.

  ![ryruow](https://user-images.githubusercontent.com/54848363/201166320-21ba8418-755f-4e77-93fd-7fc349247dd8.jpg)

2022-11-10 17:34 UTC, DammyShittu commented on README.md
- [ ] Kindly update your information here on how to set up your app using `craco` config.

- [ ] Also remember to change `math-magician` here to the correct repo name

  ![hff](https://user-images.githubusercontent.com/54848363/201165722-11d0daeb-c84f-4fc4-b63f-7a371f8f3046.jpg)

2022-11-10 17:38 UTC, juaryimami commented
Ohhh sory I was ignored the configuration file that is the problem, it
works fine in my side

Thank you!!!!.

On Thu, 10 Nov 2022, 8:34 pm Adedamola Shittu, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @juaryimami <https://github.com/juaryimami>,
> Highlights
>
> ✔️ Descriptive PR
> ✔️ Passing linters
> ✔️ Good branch name
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In package.json
> <https://github.com/juaryimami/book-store-react/pull/6#discussion_r1019426362>
> :
>
> >    "scripts": {
>
> -    "start": "react-scripts start",
>
> -    "build": "react-scripts build",
>
> -    "test": "react-scripts test",
>
> -    "eject": "react-scripts eject"
>
> +    "start": "craco start",
>
> +    "build": "craco build",
>
> +    "test": "craco test",
>
>
>
>    -
>
>    I was unable to start up your project. See the error I get. Kindly fix
>    that. I would recommend you stick to the CRA react-scripts commands.
>
>    [image: tyu]
>    <https://user-images.githubusercontent.com/54848363/201165309-b9882e45-6a25-407a-be38-6cee0d955bc8.jpg>
>    -
>
>    This is what your app looks like after I change the commands to
>    react-scripts. Kindly ensure your styling matches the design exactly
>    after fixing the issues above.
>
>    [image: ryruow]
>    <https://user-images.githubusercontent.com/54848363/201166320-21ba8418-755f-4e77-93fd-7fc349247dd8.jpg>
>
> ------------------------------
>
> In README.md
> <https://github.com/juaryimami/book-store-react/pull/6#discussion_r1019428417>
> :
>
> >  - Gitflow.
>
>  - Linters.
>
>
>
>  To get a local copy up and running follow these simple steps:
>
>
>
> -1. Go to the [repository page]( https://juaryimami.github.io/math-magician/).
>
> +1. Go to the [repository page]( https://juaryimami.github.io/book-store-react/).
>
>  2. Press the "Code" button and copy the link.
>
>  3. Clone it using git command `git clone <link>`.
>
>
>
>
>
>    -
>
>    Kindly update your information here on how to set up your app using
>    craco config.
>    -
>
>    Also remember to change math-magician here to the correct repo name
>
>    [image: hff]
>    <https://user-images.githubusercontent.com/54848363/201165722-11d0daeb-c84f-4fc4-b63f-7a371f8f3046.jpg>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/juaryimami/book-store-react/pull/6#pullrequestreview-1176215226>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALX7MXQA6BRXYCW7K5HRYTLWHUW37ANCNFSM6AAAAAAR4UEJL4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-11 05:40 UTC, topeogunleye approved these changes
### Hi @juaryimami, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
*Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 05:41 UTC, merged

2022-12-12 13:32 UTC, levy002 reviewed
## Hello @juaryimami 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] I highly recommend you use the [new professional Microverse README template](https://github.com/microverseinc/readme-template) which will document your project more professionally.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._